version: "3"

services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=acai
      - MONGO_INITDB_ROOT_PASSWORD=travel
    ports:
      - "27017:27017"
    healthcheck:
      test: [
        "CMD",
        "mongosh",
        "-u",
        "acai",
        "-p",
        "travel",
        "--authenticationDatabase",
        "admin",
        "--eval",
        "db.adminCommand('ping')"
      ]
      interval: 10s
      timeout: 10s
      retries: 5
